### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tivnet** [TIVWP/skeleton-project#1]
- [ ] .wpdb.conf and instructions
- [ ] child theme
- [ ] debug plugins and mu-plugin to disable them
- [ ] local config - copy from dist and have it in .gitignore already
